---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: docker-creds
  namespace: attendance-app
spec:
  encryptedData:
    .dockerconfigjson: AgC5kBJ5I1PK44aRyN71VyxAZzXv+oht71JNY2iNuJNnCNNbuJOIRvouX7ZC1qmfZCtYMVcDhv74t1nvO22S5VNNfjbnpFIGyUffPephtJ3yeV1YLc76IPzQL6JrbmtjaXx8OHE0z4Y595oJcc++/NNh7BNvEZOe6jPhTmah+Bc89hXtUjrgDPoptMM/x1f2mWXNlvFXmkrOt13sdDAJkpKz6sN0h1kDueNAnTXQXehYFtzDACurNIoBVj3rl3IW6OfwirVsdtFEI0abHJjeSPKONG407oIr6vU+11a/QNhjuI6ext8T56KTZoX5eo0Qj8qyZgioIgftQlyaVfbwYL9Pn+E7Sw7u4LKY5yno+kCJCvDMFgeSqlM6It87rv5oCobLo7lYzcmg3OJWNpPIFlC+k3hvJ2fHcyZkRnyTGNCeVE59Vq5RWNLcN1Hze2WvEJE/Xyxd5q7elIFgQ1F6ka3gQCy0JMarGGhG17lIVj4OBcoLAFxOjPT+pJqv/wiY5FFioZYTH15L7OBDlDA/5SFrLr+AR/hAPpreP9EVqzMW4yiAN/ESiJmNz3sqv3rQ2i9G0B5CtIaSvgXB5MXCzPej8rNIdCE4K3pIjdlsEBo5iD0JH9/FLqMsam7s1fsUhF1Cz3cRBYcreXKbxiCGtDtRjbhuLBfHc27oUlCB1vine2/vSMx+9LhsBdKPhw5IKlKLriAN7gZrAh/xZd9sZDh6+c/xetokBg3G3Sjkl5TLbPLoALUSnaFYXt2TX7Mz1SvtSzFesg0VNkhecm+gt2CSEwbONIw946aH7NatdanA9Yq5/vj6dNWgrLhCtSuYcDo7bfvp30pD6f3xLS4cSdWw1fT1SosOtbuUUlrXHHqCkw==
  template:
    metadata:
      name: docker-creds
      namespace: attendance-app
    type: kubernetes.io/dockerconfigjson
