deployment:
  name: attendance-app
  containerPort: 5000

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 2

label: attendance-app

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: chimdi247/attendance-app
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1"

imagePullSecretName: docker-creds

dockerRegistrySecret: AgC5kBJ5I1PK44aRyN71VyxAZzXv+oht71JNY2iNuJNnCNNbuJOIRvouX7ZC1qmfZCtYMVcDhv74t1nvO22S5VNNfjbnpFIGyUffPephtJ3yeV1YLc76IPzQL6JrbmtjaXx8OHE0z4Y595oJcc++/NNh7BNvEZOe6jPhTmah+Bc89hXtUjrgDPoptMM/x1f2mWXNlvFXmkrOt13sdDAJkpKz6sN0h1kDueNAnTXQXehYFtzDACurNIoBVj3rl3IW6OfwirVsdtFEI0abHJjeSPKONG407oIr6vU+11a/QNhjuI6ext8T56KTZoX5eo0Qj8qyZgioIgftQlyaVfbwYL9Pn+E7Sw7u4LKY5yno+kCJCvDMFgeSqlM6It87rv5oCobLo7lYzcmg3OJWNpPIFlC+k3hvJ2fHcyZkRnyTGNCeVE59Vq5RWNLcN1Hze2WvEJE/Xyxd5q7elIFgQ1F6ka3gQCy0JMarGGhG17lIVj4OBcoLAFxOjPT+pJqv/wiY5FFioZYTH15L7OBDlDA/5SFrLr+AR/hAPpreP9EVqzMW4yiAN/ESiJmNz3sqv3rQ2i9G0B5CtIaSvgXB5MXCzPej8rNIdCE4K3pIjdlsEBo5iD0JH9/FLqMsam7s1fsUhF1Cz3cRBYcreXKbxiCGtDtRjbhuLBfHc27oUlCB1vine2/vSMx+9LhsBdKPhw5IKlKLriAN7gZrAh/xZd9sZDh6+c/xetokBg3G3Sjkl5TLbPLoALUSnaFYXt2TX7Mz1SvtSzFesg0VNkhecm+gt2CSEwbONIw946aH7NatdanA9Yq5/vj6dNWgrLhCtSuYcDo7bfvp30pD6f3xLS4cSdWw1fT1SosOtbuUUlrXHHqCkw==
# Project namespace for your application
namespace: attendance-app

dbSecretName: db-secrets

 dbPassword: AgB6IsV2xs0FGsNxarNugDpiUnyvPZM34jJqwHRjH8qAHP3yN3Pg9cqWaixtIQjWAo9eYuXvmlL1f9sZMjZAbD313C2LtJ5fwZxjx0Mi4okzG4cre5TrS2MNuDOhnr1VprpVYcERf0yt4bUCpF7hzn6OEPnwe7nRe0CqTW9lI29T0EEScjEo5WKCQhsvUn1vevagxxhtuReJMt9Gx0ClGJ8kDT9CdyW+6gbz6FCeAT0jOfUzqsPICSEw0EI1siD/c6tn/doPmZHNwVibrYDNTjCW7LhzVeoOI0XuSmv3h6O4ValIgsl+M692uAss0OULRVdFh3FDnKFqsAWPEcTrLtx8xngnDx1kA4Vmz/hsOmK1PAR499gQzd1NRGta1a/RaVOxOP6n/44LRLVdnYeCYWMNBVPouyetx3Cb13xlZDDF6MDrK6ROyWIH7gHb++qTYh0O0hr0XEOnR0Q7BCIadDN1bZ/vClCvNvD7VScE0iplT5vxK0vE4bKYXmSPqRXcnIMq93m5Xy87FPbO4qkfHX67IiK/f9dIup1mQyV2LJTbDK/csXzsRXl8q5wkdQwdfJQiNBbcXzvayHa3SzC0qSNo3dGRtzPxIhIeNcZQfYyX6w89KkdwERwzGAP7bRJiHZryag141onj9O9+whLcPo1XCGCuLHAdf9HPNKXsDXh1nxTU8UzDvL62MFPLOWad9Vf2ZxQmhDMxv/tJFw==
 dbUser: AgAE4dsGLDi8p/7AWszaqwzVCcFpkYn3TaNeuyYUsmFnPL3KsH0MKKuvgzBC0XPPQxqJ7CB+yNwbyUZVdu9Hs5hUEqksz6irIAL8V5zFtDXBNnUgTPMPtI8n5NpzKP5j+KIFpR1bJYGnwWHvrLcZ7WFAqKqQrm3LQhBFXBCYRRiDGl2zszK/EjybwtKR5f64uDurw6FZ4+JyoNa7k62xUBWeXbkLxM40Q9jluW/U3BexYPUlfGV2n31TLnSawfp2VEbj6eWAqJHmtvakbfuH7FPzLpb73FufRh3GhVXyKtSkJ3CYN0cLYoCNL7ZO4jsGLtp2iAuXGPeSU8FHw1LO+PbaA65EjQo0grzxrtL8Zdk2Mis8mjhBbtZgUk8zHbQNgPPoUW0bt1sgJw2Y2Ty3IPFIrhOy5hTmdYUIkkswvMqVDlPHvk9Fxu0b+REJMWnBjYWC4ZPr72I/7TiNtV/PLfIu5rWNWb6KCqKEzgqpogbwz0tZipiH4fNT6WUlA50lH3Tsk/UOMcdsllGksS9iiowhG9e4OV+ZB02g5QS+vv3BimStvo4Ev35K8FWiY4TUElyeET63/wu1jd994QxS23SkDrz8NdA8qpqi96wupl7vjex51jdHE9m4Y+r7Loq3csEZ60vOoPuriCMHHMLdNkCTEiyvHVfOFiwUiBzi/37VCD2E019QuhXoedAWWNzgNYoBfvVhn9T8
  
config:
  name: db-config
  DB_HOST: 10.30.144.3
  DB_PORT: "5432"
  DB_NAME: postgres-db

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  name: attendance-app-service
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: LoadBalancer
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 5000
  targetPort: 5000

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

# This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

  scaleDown:
    stabilizationWindowSeconds: 30
    pods: 1
    periodSeconds: 30

  scaleUp:
    stabilizationWindowSeconds: 30
    pods: 1
    periodSeconds: 30

hpa:
  name: attendance-app-hpa
  targetDeployment: attendance-app


